apiVersion: core.k8s.kubemq.io/v1alpha1
kind: KubemqConnector
metadata:
  name: kubemq-sources
  namespace: kubemq
spec:
  config: |
    bindings:
    - id: 84691jbourwif3uk
      name: api-source
      properties: {}
      source:
        kind: http
        properties:
          methods: post
          path: /redis
      target:
        kind: kubemq.query
        properties:
          address: kubemq-cluster-grpc.kubemq:50000
          channel: redis
  node_port: 30000
  replicas: 1
  service_type: NodePort
  type: sources
